### ISSUE TITLE
Respect noindex: true, #nobot / #noindex / #noarchive

### ISSUE THREAD

**Issue by ericdfields** [ericdfields/threadstadon#4]

**Comment by hakamadare** [comment]
i came here looking for this feature; let me ask that you offer more fine-grained options?  for example, i don't want to deny ALL bots access to my toots, but i do specifically want to deny "thread unroller" tools such as this one. is there a particular bot user that i could block in the case of Threadstodon?  if so, please document that on the homepage and/or in the README.

**Comment by ericdfields** [comment]
@hakamadare I don't believe so. Every bot would need to opt-in to a flagging system of some sort.

**Comment by ericdfields** [comment]
@hakamadare fixed in #6
